Enable document generation using rosdoc2
ros2/common_interfaces pull request #217
Opened 2023-03-10 18:13 UTC by Yadunund

Fix missing `exec_depends` in `package.xmls` to generate documentation without any warnings using `autodoc`

2023-03-10 19:49 UTC, tfoote requested changes
If this is only necessary for doc generation we should use the 'doc_depend' tag.

2023-03-10 20:12 UTC, clalancette commented
> If this is only necessary for doc generation we should use the 'doc_depend' tag.

It turns out that it is a dependency here, we just forgot to add it in the past and got lucky since it is a transitive dependency as well.  See https://github.com/ros2/common_interfaces/blob/4bac182a0a582b5e6b784d9fa9f0dabc1aca4d35/sensor_msgs_py/sensor_msgs_py/point_cloud2.py#L45

2023-03-10 20:12 UTC, clalancette approved these changes

2023-03-13 18:23 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18217)](http://ci.ros2.org/job/ci_linux/18217/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12748)](http://ci.ros2.org/job/ci_linux-aarch64/12748/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18886)](http://ci.ros2.org/job/ci_windows/18886/)

2023-03-15 15:25 UTC, merged

2023-03-15 21:24 UTC, tfoote approved these changes
In that case lgtm