Add PoseStampedArray
ros2/common_interfaces pull request #262
Opened 2024-12-03 11:00 UTC by tonynajjar

The need originated from [here](https://github.com/ros-navigation/navigation2/pull/4771#:~:text=Also%2C%20food%20for%20thought%2C%20this%20seems%20like%20a%20good%20geometry_msgs%20improvement%20rather%20than%20a%20nav2_msgs%20improvement%20to%20add%20PosesStamped.%20Maybe%20we%20should%20file%20a%20ticket%20over%20there%20and%20ask%20%40tfoote%20if%20he%27s%20open%20to%20that%20contribution). @SteveMacenski

2024-12-03 15:03 UTC, mjcarroll approved these changes
No arguments from me.

Should we potentially add a comment here about what the difference between the root `std_msgs/Header` and the per-message `std_msgs/Header` mean here, or is that entirely application specific.

2024-12-03 15:45 UTC, SteveMacenski commented
I think the global message stamp could be removed?

2024-12-03 16:01 UTC, tonynajjar commented
> I think the global message stamp could be removed?

Would you then also remove this one? -> https://github.com/ros2/common_interfaces/blob/rolling/nav_msgs/msg/Path.msg
Same concept no?

2024-12-03 17:06 UTC, SteveMacenski commented
The path's header is for the path, the pose headers are for each of the poses in the path if it were a time denoted trajectory. Admittedly its rarely (if ever) used that way, but it is conceptually the right way for the path to be structured for kinodynamic paths, should uses need to represent one.

Does the application of `PoseStampedArray` have a similar need? I'm ambivalent, just couldn't think of a reason why we needed it for `PoseStampedArray`

2024-12-03 17:19 UTC, tonynajjar commented
Okay. I also don't see a reason to keep it but I wanted to stay consistent. It makes sense though why `nav_msgs/Path` would have a header. Removed

2024-12-05 14:17 UTC, tonynajjar commented
While working with this message we actually found a potential use for the global header. I added a comment but see [here](https://github.com/ros-navigation/navigation2/pull/4771/files#r1868577905) for more info. Feel free to propose a reformulation

2024-12-05 15:17 UTC, SteveMacenski approved these changes

2024-12-05 15:19 UTC, SteveMacenski commented
@mjcarroll I think this is in the final form with the header description. Do we need another maintainer to review or can we ship?

2024-12-05 15:35 UTC, clalancette requested changes

2024-12-05 15:35 UTC, clalancette commented on geometry_msgs/msg/PoseStampedArray.msg
> +# The global header will store the time at which the poses were computed (not to confuse with the stamps of the poses themselves)
```suggestion
# The global header will store the time at which the poses were computed (not to be confused with the stamps of the poses themselves)
```

2024-12-05 15:35 UTC, clalancette commented on geometry_msgs/msg/PoseStampedArray.msg
> +PoseStamped[] poses
Please add a newline at the end of the file.

2024-12-09 08:37 UTC, tonynajjar commented
Thanks for the review, changes were made, anything else?

2024-12-11 19:12 UTC, SteveMacenski commented
We're also planning on using this for the NavigateToPose interface - which makes alot more sense than our `vector<PoseStamped>` for a list of goal representation so we can have a stamp to gauge the age of the original request. We're finding more places to use this by the day :-)

2024-12-12 09:26 UTC, tonynajjar commented
> We're also planning on using this for the NavigateToPose interface

NavigateThroughPoses*

2025-01-02 08:42 UTC, tonynajjar commented
Happy new year! (ping in disguise @clalancette 😄 )

2025-01-06 18:02 UTC, mjcarroll approved these changes

2025-01-06 18:14 UTC, mjcarroll commented
Pulls: ros2/common_interfaces#262
Gist: https://gist.githubusercontent.com/mjcarroll/e51db32e9e99205be4fa32319946c28b/raw/5e9a971bdd5ed5eb905513bd6477c1a698030d59/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15039
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22355)](http://ci.ros2.org/job/ci_linux/22355/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16618)](http://ci.ros2.org/job/ci_linux-aarch64/16618/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1886)](http://ci.ros2.org/job/ci_linux-rhel/1886/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23146)](http://ci.ros2.org/job/ci_windows/23146/)

2025-01-07 01:06 UTC, SteveMacenski commented
@mjcarroll they've all passed :-)

2025-01-07 08:10 UTC, ahcorde approved these changes

2025-01-07 08:11 UTC, merged

2025-01-07 13:06 UTC, gavanderhoorn commented
It's surprising to see this merged, especially after the many discussions about extending `std_msgs` with more messages with low semantic value (of which the linked https://github.com/ros/common_msgs/issues/144 is an example).

What changed? Different maintainers, changed opinions, evolution of best-practices? All of the above?

2025-01-13 23:49 UTC, Swepz commented
Friendly reminder to bump tag :)
![image](https://github.com/user-attachments/assets/31056bc9-f7cb-445e-bc47-6eeb102d447b)

2025-01-30 23:34 UTC, tfoote commented
I'd like to review the naming and documentation of this before we make a release to be sure we've locked down the semantics of this message. I've added it to the PMC meeting agenda for next week.